// Records the example output shown under every lesson snippet → outputs.js
//
//   node tools/build-outputs.mjs
//
// Serves the app on 127.0.0.1, opens it in headless Chrome with a throwaway profile (so the dataset is
// generated fresh, exactly as a first-time visitor gets it), runs every runnable snippet in course order,
// and saves the recorded query results. Re-run it whenever you add or change a snippet.
// Needs Chrome or Edge; set CHROME=/path/to/chrome if it isn't found.
import http from 'node:http';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = normalize(fileURLToPath(new URL('..', import.meta.url)));
const PORT = Number(process.env.PORT || 8799);
const TIMEOUT_MS = 6 * 60 * 1000;
const TYPES = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json' };

const candidates = [
  process.env.CHROME,
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser',
].filter(Boolean);
const chromePath = candidates.find((p) => existsSync(p));
if (!chromePath) { console.error('Chrome/Edge not found. Set CHROME=/path/to/chrome.'); process.exit(1); }

let finish;
const done = new Promise((r) => { finish = r; });

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://127.0.0.1:${PORT}`);
  if (req.method === 'POST' && url.pathname === '/__outputs') {
    const chunks = []; for await (const c of req) chunks.push(c);
    const data = JSON.parse(Buffer.concat(chunks).toString('utf8'));
    const js = '// Generated by tools/build-outputs.mjs — recorded example output for every lesson snippet. Do not edit.\n'
      + `window.PGLAB_OUTPUTS = ${JSON.stringify(data)};\n`;
    await writeFile(join(ROOT, 'outputs.js'), js);
    res.writeHead(200).end('ok');
    finish({ snippets: Object.keys(data.snippets).length, bytes: js.length, engine: data.engine });
    return;
  }
  const rel = url.pathname === '/' ? 'index.html' : decodeURIComponent(url.pathname).replace(/^\/+/, '');
  const path = normalize(join(ROOT, rel));
  if (!path.startsWith(ROOT)) { res.writeHead(403).end(); return; }
  if (rel === 'outputs.js') { res.writeHead(200, { 'content-type': TYPES['.js'] }).end('window.PGLAB_OUTPUTS = null;'); return; }
  try {
    res.writeHead(200, { 'content-type': TYPES[extname(path)] || 'application/octet-stream', 'cache-control': 'no-store' });
    res.end(await readFile(path));
  } catch { res.writeHead(404).end('not found'); }
});
await new Promise((r) => server.listen(PORT, '127.0.0.1', r));

const profile = mkdtempSync(join(tmpdir(), 'pglab-build-'));
const chrome = spawn(chromePath, [
  '--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check', '--disable-extensions',
  `--user-data-dir=${profile}`, '--enable-logging=stderr', '--v=0', '--remote-debugging-port=0',
  `http://127.0.0.1:${PORT}/index.html?build-outputs#expectations`,
], { stdio: ['ignore', 'ignore', 'pipe'] });
console.log(`Recording snippet outputs with ${chromePath.split(/[\\/]/).pop()} (building the dataset first, ~30 s)…`);
let seen = 0;
chrome.stderr.setEncoding('utf8');
chrome.stderr.on('data', (chunk) => {
  for (const m of chunk.matchAll(/PGLAB-BUILD ([^"]*)/g)) {
    const msg = m[1];
    if (msg.startsWith('done') || msg.startsWith('failed') || msg.includes('warning') || msg.includes('error')) console.log('  ' + msg);
    else if (++seen % 10 === 0) console.log(`  ${seen} snippets…`);
  }
});

const timer = setTimeout(() => finish({ error: 'timed out' }), TIMEOUT_MS);
const result = await done;
clearTimeout(timer);
chrome.kill();
server.close();
setTimeout(() => { try { rmSync(profile, { recursive: true, force: true }); } catch { /* Chrome may still hold files */ } }, 1500);
if (result.error) { console.error('Failed: ' + result.error); process.exit(1); }
console.log(`Wrote outputs.js: ${result.snippets} snippets, ${(result.bytes / 1024).toFixed(0)} KB (${result.engine}).`);
